### ISSUE TITLE
Question on multiple database for multiple users?

### ISSUE THREAD

**Issue by killmasta93** [hurlenko/filebrowser-docker#38]
Hi
I was wondering if someone could shed some light, Currently trying to create multiple databases but each database route to give to a certain user
ex: user 1 have access test folder
user 2 have access only test2 folder

This is what i have on docker compose

```
version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8188:8080
    volumes:
      - /test:/data/first
      - /test2:/data/second
      - config:/config
    restart: always
volumes:
  config:
   driver: local-persist
   driver_opts:
     mountpoint: /root/filebrowser
```

when i try to change the scope to /data2 says location does not exist so not sure what else to do?

i have read https://github.com/hurlenko/filebrowser-docker/issues/7

but does not say about scope permissions per user

Thank you
