### ISSUE TITLE
User docker-compose

### ISSUE THREAD

**Issue by Erriez** [hurlenko/filebrowser-docker#8]
Thanks for creating this great Docker. I'm running it on a Raspberry Pi4 aarch64 with docker-compose.yml and I'd like to edit / create files as normal user:

```yaml
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: always
    user: 1000:1000
    volumes:
      - ${VOLUME_DIR}/filebrowser/config:/config
      - ${VOLUME_DIR}/share:/data
```

Creating the container results in:
`filebrowser      | 2021/02/04 20:53:30 open /config/filebrowser.db: permission denied`

I found a workaround to run the container without `user:` first as root:root which creates `${VOLUME_DIR}/filebrowser/config`.
Then `sudo chown 1000:1000 -R ${VOLUME_DIR}/filebrowser/config/filebrowser.db` and recreate the container. Then it works.

What could be the problem?
